### ISSUE TITLE
Unimplemented Operation: opx.sysram1.ROMVersionBuild

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#174] opened 2022-02-07 18:05 UTC
Unimplemented operation opx.sysram1.ROMVersionBuild
PSITRIS\LOADFILES:000046BF: FF [NextOpcodeTable] 18 CallOpxFunc 2 12 (sysram1 ROMVersionBuild)
PSITRIS\PSITRIS:00000363: 53 [RunProcedure] 0x02DD (name="LOADFILES" nargs=0)
stack traceback:
	[C]: in function 'error'
	init.lua:444: in function 'unimplemented'
	sysram1.lua:98: in function 'opx.sysram1.ROMVersionBuild'
	ops.lua:2294: in function 'ops.CallOpxFunc'
	ops.lua:2180: in function 'ops.NextOpcodeTable'
	runtime.lua:806: in function <runtime.lua:791>
	[C]: in function 'xpcall'
	runtime.lua:923: in method 'pcallProc'
	runtime.lua:1278: in function 'runtime.runOpo'

**Comment by tomsci** [comment] 2022-02-07 18:11
Duplicate of #171

**Closed by tomsci** 2022-02-07 18:11 UTC
Labels: bug, facerake
