### ISSUE TITLE
Internal Error: database.lua:503: Unsupported field type!

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#330] opened 2024-08-18 21:00 UTC
## Description

- Conquête (https://archive.org/download/3-libjune-05/3LIBJUNE05.iso/library%2Fepocgames%2Fcnquk134%2FConqueteUK.SIS)

## Details

```
database.lua:503: Unsupported field type!
CONQUETE\CHARGE:00005CBA: B4 [Open] logName=0 fields=FNOM$, FNUM$, FCONT$, FCODE$, FXC$, FYC$, FDIF$, FVOISINS$
CONQUETE\INITIALISE:00000349: 53 [RunProcedure] 0x0225 (name="CHARGE" nargs=0)
stack traceback:
	[C]: in function 'assert'
	database.lua:503: in method 'readTableDefinition'
	database.lua:415: in function <database.lua:373>
	(...tail calls...)
	runtime.lua:628: in method 'openDb'
	ops.lua:1587: in function 'ops.Open'
	runtime.lua:859: in function <runtime.lua:844>
	[C]: in function 'xpcall'
	runtime.lua:978: in method 'pcallProc'
	runtime.lua:1242: in function 'runtime.runOpo'
```

**Comment by tomsci** [comment] 2024-08-19 22:12
duplicate of #331

**Closed by tomsci** 2024-08-19 22:12 UTC
Labels: bug, internal-error
